[accesslog]
[api]
  insecure=true
  dashboard=true
  debug=true

[log]
  level="DEBUG"
  

[entryPoints]
  [entryPoints.web]
    address=":8082"

[providers.file]
  directory = "/home/bakiscofield/Documents/traefik/services/"
  watch = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

