
  [http.routers]
    [http.routers.xavki_route]
      entryPoints = ["web"]
      service = "xavki"
      rule = "Path(`/`)"
  [http.services]
    [http.services.xavki]
      [http.services.xavki.loadBalancer]
        [[http.services.xavki.loadBalancer.servers]]
          url = "http://127.0.0.1:8088"
        [[http.services.xavki.loadBalancer.servers]]
          url = "http://127.0.0.1:8083"
        [[http.services.xavki.loadBalancer.servers]]
          url = "http://127.0.0.1:8084"

